server:
  port: 8080

spring:
  application:
    name: jpa
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost:3306}/${DB_NAME:sp3-jpa}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=${DB_SSL:false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:666666}
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 20
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 5000
      # 检测连接是否有效
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
