CREATE TABLE `image_info`  (
   `id` bigint NOT NULL AUTO_INCREMENT,
   `url` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '图片地址',
   `rating` int NULL DEFAULT NULL COMMENT '图片评分',
   `detail` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '图片描述',
   `create_time` datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
   `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
   `del` int NOT NULL DEFAULT 0 COMMENT '逻辑删除：0->可用；1->删除',
   PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 101 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '图片信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of image_info
-- ----------------------------
INSERT INTO `image_info` VALUES (1, 'https://drive.leungonn4.com/HealthBabyCare', 1, 'What you get by achieving your goals is not as important as what you become by achieving your goals.', '2023-11-09 07:57:35', NULL, 0);
INSERT INTO `image_info` VALUES (2, 'https://drive.tsang1954.com/IndustrialScientificSupplies', 4, 'Secure SHell (SSH) is a program to log in into another computer over a network, execute commands on a remote server, and move files from one machine to another. Such sessions are also                 ', '2023-11-01 12:23:55', NULL, 0);
INSERT INTO `image_info` VALUES (3, 'http://drive.moorearthur.com/Baby', 2, 'Navicat allows you to transfer data from one database and/or schema to another with detailed analytical process. The Synchronize to Database function will give you a full picture of                   ', '2023-11-19 21:01:59', NULL, 0);
INSERT INTO `image_info` VALUES (4, 'http://image.wcy.com/BeautyPersonalCare', 3, 'After logged in the Navicat Cloud feature, the Navigation pane will be divided into Navicat Cloud and My Connections sections.', '2023-11-17 09:18:04', NULL, 0);
INSERT INTO `image_info` VALUES (5, 'https://drive.lfu.com/ToysGames', 2, 'I destroy my enemies when I make them my friends.', '2023-11-08 04:12:09', NULL, 0);
INSERT INTO `image_info` VALUES (6, 'https://drive.zqi227.com/ToysGames', 4, 'Navicat Monitor can be installed on any local computer or virtual machine and does not require any software installation on the servers being monitored.', '2023-11-11 09:12:56', NULL, 0);
INSERT INTO `image_info` VALUES (7, 'https://image.momoeyamaguchi.com/Beauty', 0, 'You will succeed because most people are lazy.', '2023-11-08 06:12:06', NULL, 0);
INSERT INTO `image_info` VALUES (8, 'https://image.jenashley.com/FilmSupplies', 3, 'The repository database can be an existing MySQL, MariaDB, PostgreSQL, SQL Server, or Amazon RDS instance.', '2023-11-18 10:58:57', NULL, 0);
INSERT INTO `image_info` VALUES (9, 'https://image.yanziyi87.com/ArtsHandicraftsSewing', 3, 'If the Show objects under schema in navigation pane option is checked at the Preferences window, all database objects are also displayed in the pane.', '2023-11-16 01:34:40', NULL, 0);
INSERT INTO `image_info` VALUES (10, 'https://image.kikuchiyuito.com/HealthBabyCare', 3, 'Difficult circumstances serve as a textbook of life for people. HTTP Tunneling is a method for connecting to a server that uses the same protocol (http://) and the same port (port 80)                 ', '2023-11-18 01:07:31', NULL, 0);
INSERT INTO `image_info` VALUES (11, 'https://image.hokyaufo.com/Baby', 1, 'Such sessions are also susceptible to session hijacking, where a malicious user takes over your session once you have authenticated. There is no way to happiness. Happiness is the way.', '2023-11-20 06:48:44', NULL, 0);
INSERT INTO `image_info` VALUES (12, 'http://drive.asaku.com/CDsVinyl', 2, 'Navicat authorizes you to make connection to remote servers running on different platforms (i.e. Windows, macOS, Linux and UNIX), and supports PAM and GSSAPI authentication.', '2023-11-15 01:26:09', NULL, 0);
INSERT INTO `image_info` VALUES (13, 'https://image.kkaryan7.com/PetSupplies', 3, 'In the middle of winter I at last discovered that there was in me an invincible summer. Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from.', '2023-11-12 00:28:30', NULL, 0);
INSERT INTO `image_info` VALUES (14, 'https://drive.kudoshin.com/HouseholdKitchenAppliances', 5, 'If it scares you, it might be a good thing to try. If it scares you, it might be a good thing to try.', '2023-11-10 10:14:03', NULL, 0);
INSERT INTO `image_info` VALUES (15, 'http://drive.wingkuenm.com/PetSupplies', 4, 'I will greet this day with love in my heart. Navicat Data Modeler is a powerful and cost-effective database design tool which helps you build high-quality conceptual, logical and physical data models.', '2023-11-14 21:48:15', NULL, 0);
INSERT INTO `image_info` VALUES (16, 'https://drive.leehuimei1.com/HouseholdKitchenAppliances', 4, 'Typically, it is employed as an encrypted version of Telnet. You must be the change you wish to see in the world. I will greet this day with love in my heart. Secure Sockets Layer(SSL)                ', '2023-11-03 13:37:27', NULL, 0);
INSERT INTO `image_info` VALUES (17, 'http://image.yamatonis.com/HealthBabyCare', 2, 'The Synchronize to Database function will give you a full picture of all database differences. I destroy my enemies when I make them my friends.', '2023-11-12 15:29:23', NULL, 0);
INSERT INTO `image_info` VALUES (18, 'http://drive.ross902.com/AppsGames', 4, 'What you get by achieving your goals is not as important as what you become by achieving your goals. The first step is as good as half over.', '2023-11-09 13:32:16', NULL, 0);
INSERT INTO `image_info` VALUES (19, 'https://drive.joannesullivan.com/ComputersElectronics', 4, 'Anyone who has never made a mistake has never tried anything new.', '2023-11-13 22:01:26', NULL, 0);
INSERT INTO `image_info` VALUES (20, 'http://drive.wingsuen228.com/VideoGames', 1, 'Optimism is the one quality more associated with success and happiness than any other.', '2023-11-03 05:24:58', NULL, 0);
INSERT INTO `image_info` VALUES (21, 'http://image.ksakur.com/ToolsHomeDecoration', 3, 'The Main Window consists of several toolbars and panes for you to work on connections, database objects and advanced tools. HTTP Tunneling is a method for connecting to a server that                  ', '2023-11-10 08:04:46', NULL, 0);
INSERT INTO `image_info` VALUES (22, 'http://image.tangj1209.com/Food', 2, 'I destroy my enemies when I make them my friends. The past has no power over the present moment.', '2023-11-12 08:00:15', NULL, 0);
INSERT INTO `image_info` VALUES (23, 'http://drive.wus.com/Baby', 1, 'The past has no power over the present moment.', '2023-11-13 20:46:40', NULL, 0);
INSERT INTO `image_info` VALUES (24, 'https://image.kalingkoon.com/IndustrialScientificSupplies', 0, 'The Information Pane shows the detailed object information, project activities, the DDL of database objects, object dependencies, membership of users/roles and preview.', '2023-11-02 07:35:45', NULL, 0);
INSERT INTO `image_info` VALUES (25, 'http://image.wlan.com/HealthBabyCare', 0, 'The Information Pane shows the detailed object information, project activities, the DDL of database objects, object dependencies, membership of users/roles and preview.', '2023-11-18 10:13:25', NULL, 0);
INSERT INTO `image_info` VALUES (26, 'http://drive.philippayne.com/Others', 3, 'To get a secure connection, the first thing you need to do is to install OpenSSL Library and download Database Source.', '2023-11-09 05:19:28', NULL, 0);
INSERT INTO `image_info` VALUES (27, 'http://image.wingkuen8.com/HealthBabyCare', 0, 'Champions keep playing until they get it right. Creativity is intelligence having fun.', '2023-11-01 07:52:34', NULL, 0);
INSERT INTO `image_info` VALUES (28, 'http://drive.miyazaki1028.com/ClothingShoesandJewelry', 2, 'Genius is an infinite capacity for taking pains.', '2023-11-12 17:59:58', NULL, 0);
INSERT INTO `image_info` VALUES (29, 'http://drive.saraito.com/HouseholdKitchenAppliances', 4, 'A man is not old until regrets take the place of dreams. It is used while your ISPs do not allow direct connections, but allows establishing HTTP connections.', '2023-11-06 03:07:39', NULL, 0);
INSERT INTO `image_info` VALUES (30, 'https://drive.mitsuki1963.com/CDsVinyl', 1, 'A query is used to extract data from the database in a readable format according to the user\'s request.', '2023-11-09 00:14:43', NULL, 0);
INSERT INTO `image_info` VALUES (31, 'http://image.ming82.com/Baby', 0, 'Typically, it is employed as an encrypted version of Telnet. Navicat Monitor is a safe, simple and agentless remote server monitoring tool that is packed with powerful features to make                ', '2023-11-13 17:03:44', NULL, 0);
INSERT INTO `image_info` VALUES (32, 'https://image.xxiaom.com/Handcrafts', 5, 'A query is used to extract data from the database in a readable format according to the user\'s request.', '2023-11-10 00:54:33', NULL, 0);
INSERT INTO `image_info` VALUES (33, 'https://image.wachunyu.com/CollectiblesFineArt', 1, 'In other words, Navicat provides the ability for data in different databases and/or schemas to be kept up-to-date so that each repository contains the same information.', '2023-11-12 00:31:10', NULL, 0);
INSERT INTO `image_info` VALUES (34, 'http://drive.kdaisuke.com/ToolsHomeDecoration', 3, 'Champions keep playing until they get it right. With its well-designed Graphical User Interface(GUI), Navicat lets you quickly and easily create, organize, access and share information                ', '2023-11-09 08:18:02', NULL, 0);
INSERT INTO `image_info` VALUES (35, 'http://drive.willim.com/Baby', 3, 'You will succeed because most people are lazy. Navicat authorizes you to make connection to remote servers running on different platforms (i.e. Windows, macOS, Linux and UNIX), and                    ', '2023-11-04 13:08:20', NULL, 0);
INSERT INTO `image_info` VALUES (36, 'http://drive.panlu.com/Beauty', 2, 'If your Internet Service Provider (ISP) does not provide direct access to its server, Secure Tunneling Protocol (SSH) / HTTP is another solution. Navicat Data Modeler enables you to                   ', '2023-11-20 22:02:12', NULL, 0);
INSERT INTO `image_info` VALUES (37, 'https://drive.garda.com/CDsVinyl', 2, 'Navicat allows you to transfer data from one database and/or schema to another with detailed analytical process.', '2023-11-11 20:06:36', NULL, 0);
INSERT INTO `image_info` VALUES (38, 'https://drive.roystewart69.com/Food', 1, 'Flexible settings enable you to set up a custom key for comparison and synchronization. To successfully establish a new connection to local/remote server - no matter via SSL or SSH,                   ', '2023-11-12 01:34:52', NULL, 0);
INSERT INTO `image_info` VALUES (39, 'https://image.kdav.com/FilmSupplies', 3, 'HTTP Tunneling is a method for connecting to a server that uses the same protocol (http://) and the same port (port 80) as a web server does. Navicat provides powerful tools for working               ', '2023-11-19 10:36:33', NULL, 0);
INSERT INTO `image_info` VALUES (40, 'https://drive.huimy.com/FilmSupplies', 4, 'If the Show objects under schema in navigation pane option is checked at the Preferences window, all database objects are also displayed in the pane.', '2023-11-18 07:49:26', NULL, 0);
INSERT INTO `image_info` VALUES (41, 'http://drive.swsi.com/BaggageTravelEquipment', 3, 'If the Show objects under schema in navigation pane option is checked at the Preferences window, all database objects are also displayed in the pane.', '2023-11-17 22:08:00', NULL, 0);
INSERT INTO `image_info` VALUES (42, 'http://image.ruixia.com/FilmSupplies', 1, 'Anyone who has ever made anything of importance was disciplined.', '2023-11-09 00:09:32', NULL, 0);
INSERT INTO `image_info` VALUES (43, 'https://image.shehwy02.com/ArtsHandicraftsSewing', 1, 'Navicat Monitor requires a repository to store alerts and metrics for historical analysis.', '2023-11-10 08:26:42', NULL, 0);
INSERT INTO `image_info` VALUES (44, 'http://image.laitw507.com/BaggageTravelEquipment', 2, 'The Synchronize to Database function will give you a full picture of all database differences. Monitored servers include MySQL, MariaDB and SQL Server, and compatible with cloud databases             ', '2023-11-11 04:49:10', NULL, 0);
INSERT INTO `image_info` VALUES (45, 'http://drive.tongchim17.com/BaggageTravelEquipment', 3, 'Navicat allows you to transfer data from one database and/or schema to another with detailed analytical process. If opportunity doesn’t knock, build a door. Export Wizard allows you                 ', '2023-11-06 01:06:58', NULL, 0);
INSERT INTO `image_info` VALUES (46, 'http://drive.kn7.com/Baby', 4, 'Import Wizard allows you to import data to tables/collections from CSV, TXT, XML, DBF and more.', '2023-11-02 17:43:46', NULL, 0);
INSERT INTO `image_info` VALUES (47, 'https://image.stevenrogers3.com/CenturionGardenOutdoor', 2, 'I will greet this day with love in my heart. A man is not old until regrets take the place of dreams. Navicat allows you to transfer data from one database and/or schema to another                    ', '2023-11-01 04:29:50', NULL, 0);
INSERT INTO `image_info` VALUES (48, 'http://image.tianzi.com/ToysGames', 2, 'The Information Pane shows the detailed object information, project activities, the DDL of database objects, object dependencies, membership of users/roles and preview. All the Navicat                ', '2023-11-11 19:49:41', NULL, 0);
INSERT INTO `image_info` VALUES (49, 'http://image.hasegawanan.com/HouseholdKitchenAppliances', 4, 'A man’s best friends are his ten fingers. In other words, Navicat provides the ability for data in different databases and/or schemas to be kept up-to-date so that each repository                   ', '2023-11-04 13:02:48', NULL, 0);
INSERT INTO `image_info` VALUES (50, 'https://image.lu2001.com/Others', 2, 'What you get by achieving your goals is not as important as what you become by achieving your goals. Instead of wondering when your next vacation is, maybe you should set up a life                    ', '2023-11-08 19:06:43', NULL, 0);
INSERT INTO `image_info` VALUES (51, 'https://image.mz525.com/Appliances', 4, 'Navicat authorizes you to make connection to remote servers running on different platforms (i.e. Windows, macOS, Linux and UNIX), and supports PAM and GSSAPI authentication.', '2023-11-02 21:37:39', NULL, 0);
INSERT INTO `image_info` VALUES (52, 'http://image.mitsukisasaki.com/Baby', 4, 'You will succeed because most people are lazy. The Navigation pane employs tree structure which allows you to take action upon the database and their objects through their pop-up menus                ', '2023-11-18 10:44:45', NULL, 0);
INSERT INTO `image_info` VALUES (53, 'https://image.garzamari1124.com/Books', 4, 'Navicat provides powerful tools for working with queries: Query Editor for editing the query text directly, and Query Builder, Find Builder or Aggregate Builder for building queries visually.', '2023-11-05 14:22:43', NULL, 0);
INSERT INTO `image_info` VALUES (54, 'https://image.ksaku.com/SportsOutdoor', 0, 'Champions keep playing until they get it right. Actually it is just in an idea when feel oneself can achieve and cannot achieve.', '2023-11-06 09:49:28', NULL, 0);
INSERT INTO `image_info` VALUES (55, 'http://drive.yunxiqi.com/HouseholdKitchenAppliances', 2, 'You cannot save people, you can just love them. Such sessions are also susceptible to session hijacking, where a malicious user takes over your session once you have authenticated.', '2023-11-01 20:49:00', NULL, 0);
INSERT INTO `image_info` VALUES (56, 'http://drive.cheng1979.com/CenturionGardenOutdoor', 1, 'In a Telnet session, all communications, including username and password, are transmitted in plain-text, allowing anyone to listen-in on your session and steal passwords and other information.', '2023-11-01 18:12:31', NULL, 0);
INSERT INTO `image_info` VALUES (57, 'https://image.chanht907.com/Baby', 4, 'Always keep your eyes open. Keep watching. Because whatever you see can inspire you.', '2023-11-07 09:30:06', NULL, 0);
INSERT INTO `image_info` VALUES (58, 'http://image.ayatokoji.com/FilmSupplies', 0, 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your connection settings, queries, model files, and virtual group; your database passwords            ', '2023-11-02 17:54:52', NULL, 0);
INSERT INTO `image_info` VALUES (59, 'http://drive.kenta703.com/CDsVinyl', 3, 'Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from.', '2023-11-03 19:29:07', NULL, 0);
INSERT INTO `image_info` VALUES (60, 'https://drive.saitoakina6.com/BeautyPersonalCare', 2, 'Secure SHell (SSH) is a program to log in into another computer over a network, execute commands on a remote server, and move files from one machine to another.', '2023-11-20 23:12:11', NULL, 0);
INSERT INTO `image_info` VALUES (61, 'https://drive.maoan821.com/Appliances', 3, 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your connection settings, queries, model files, and virtual group; your database passwords            ', '2023-11-08 11:26:30', NULL, 0);
INSERT INTO `image_info` VALUES (62, 'https://image.hikarishibata.com/ToolsHomeDecoration', 4, 'A man’s best friends are his ten fingers. Anyone who has never made a mistake has never tried anything new.', '2023-11-14 02:21:22', NULL, 0);
INSERT INTO `image_info` VALUES (63, 'http://drive.houlan.com/PetSupplies', 4, 'Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from. If it scares you, it might be a good thing to try. All journeys have                   ', '2023-11-18 19:43:43', NULL, 0);
INSERT INTO `image_info` VALUES (64, 'https://image.chin79.com/CDsVinyl', 5, 'Navicat allows you to transfer data from one database and/or schema to another with detailed analytical process.', '2023-11-08 03:54:31', NULL, 0);
INSERT INTO `image_info` VALUES (65, 'https://drive.zhennanw.com/Others', 1, 'To get a secure connection, the first thing you need to do is to install OpenSSL Library and download Database Source. Instead of wondering when your next vacation is, maybe you should                ', '2023-11-07 07:28:58', NULL, 0);
INSERT INTO `image_info` VALUES (66, 'http://drive.wandaevans.com/Others', 4, 'Navicat Monitor can be installed on any local computer or virtual machine and does not require any software installation on the servers being monitored.', '2023-11-08 06:32:22', NULL, 0);
INSERT INTO `image_info` VALUES (67, 'https://drive.lanshe75.com/FilmSupplies', 4, 'A man’s best friends are his ten fingers. Difficult circumstances serve as a textbook of life for people. It wasn’t raining when Noah built the ark.', '2023-11-10 08:13:27', NULL, 0);
INSERT INTO `image_info` VALUES (68, 'https://image.lwaihan.com/Baby', 3, 'It can also manage cloud databases such as Amazon Redshift, Amazon RDS, Alibaba Cloud. Features in Navicat are sophisticated enough to provide professional developers for all their                    ', '2023-11-07 17:18:47', NULL, 0);
INSERT INTO `image_info` VALUES (69, 'https://drive.eitamori.com/ToysGames', 4, 'Navicat provides powerful tools for working with queries: Query Editor for editing the query text directly, and Query Builder, Find Builder or Aggregate Builder for building queries visually.', '2023-11-16 16:23:14', NULL, 0);
INSERT INTO `image_info` VALUES (70, 'https://drive.hyng.com/ClothingShoesandJewelry', 3, 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your connection settings, queries, model files, and virtual group; your database passwords            ', '2023-11-01 17:30:44', NULL, 0);
INSERT INTO `image_info` VALUES (71, 'http://image.yinsh80.com/HealthBabyCare', 3, 'The Synchronize to Database function will give you a full picture of all database differences.', '2023-11-11 04:38:07', NULL, 0);
INSERT INTO `image_info` VALUES (72, 'http://drive.willierice9.com/ComputersElectronics', 4, 'Navicat Cloud provides a cloud service for synchronizing connections, queries, model files and virtual group information from Navicat, other Navicat family members, different machines                 ', '2023-11-09 20:56:44', NULL, 0);
INSERT INTO `image_info` VALUES (73, 'http://image.garcia02.com/FilmSupplies', 2, 'The reason why a great man is great is that he resolves to be a great man.', '2023-11-18 07:38:22', NULL, 0);
INSERT INTO `image_info` VALUES (74, 'https://image.yuely809.com/CenturionGardenOutdoor', 1, 'A man is not old until regrets take the place of dreams. A comfort zone is a beautiful place, but nothing ever grows there.', '2023-11-10 09:53:05', NULL, 0);
INSERT INTO `image_info` VALUES (75, 'https://drive.cshihan.com/Beauty', 3, 'Monitored servers include MySQL, MariaDB and SQL Server, and compatible with cloud databases like Amazon RDS, Amazon Aurora, Oracle Cloud, Google Cloud and Microsoft Azure.', '2023-11-12 09:00:43', NULL, 0);
INSERT INTO `image_info` VALUES (76, 'http://drive.yuxiao1.com/ToolsHomeDecoration', 0, 'To open a query using an external editor, control-click it and select Open with External Editor. You can set the file path of an external editor in Preferences.', '2023-11-11 18:51:13', NULL, 0);
INSERT INTO `image_info` VALUES (77, 'https://image.kongxia1209.com/Food', 5, 'If opportunity doesn’t knock, build a door. The Main Window consists of several toolbars and panes for you to work on connections, database objects and advanced tools.', '2023-11-03 05:22:25', NULL, 0);
INSERT INTO `image_info` VALUES (78, 'https://drive.glaryan73.com/BeautyPersonalCare', 2, 'In the middle of winter I at last discovered that there was in me an invincible summer.', '2023-11-20 12:01:30', NULL, 0);
INSERT INTO `image_info` VALUES (79, 'http://image.mochiehlun4.com/CenturionGardenOutdoor', 5, 'Navicat Cloud provides a cloud service for synchronizing connections, queries, model files and virtual group information from Navicat, other Navicat family members, different machines                 ', '2023-11-05 04:47:01', NULL, 0);
INSERT INTO `image_info` VALUES (80, 'https://image.tanfat00.com/Baby', 0, 'Success consists of going from failure to failure without loss of enthusiasm.', '2023-11-16 12:57:32', NULL, 0);
INSERT INTO `image_info` VALUES (81, 'https://drive.jianxiuying6.com/ToolsHomeDecoration', 4, 'Navicat allows you to transfer data from one database and/or schema to another with detailed analytical process.', '2023-11-06 04:40:25', NULL, 0);
INSERT INTO `image_info` VALUES (82, 'https://image.ryot2.com/Baby', 4, 'Sometimes you win, sometimes you learn. Navicat Cloud provides a cloud service for synchronizing connections, queries, model files and virtual group information from Navicat, other                    ', '2023-11-17 07:05:20', NULL, 0);
INSERT INTO `image_info` VALUES (83, 'http://image.shezhennan10.com/Appliances', 5, 'It wasn’t raining when Noah built the ark.', '2023-11-13 18:53:15', NULL, 0);
INSERT INTO `image_info` VALUES (84, 'https://image.yeungky.com/HouseholdKitchenAppliances', 4, 'I may not have gone where I intended to go, but I think I have ended up where I needed to be.', '2023-11-06 18:50:47', NULL, 0);
INSERT INTO `image_info` VALUES (85, 'http://drive.ck2007.com/ToysGames', 2, 'To successfully establish a new connection to local/remote server - no matter via SSL or SSH, set the database login information in the General tab.', '2023-11-12 17:07:52', NULL, 0);
INSERT INTO `image_info` VALUES (86, 'http://image.shebennett.com/CellPhonesAccessories', 2, 'The Navigation pane employs tree structure which allows you to take action upon the database and their objects through their pop-up menus quickly and easily. Navicat 15 has added support              ', '2023-11-02 17:41:56', NULL, 0);
INSERT INTO `image_info` VALUES (87, 'http://drive.goju.com/CellPhonesAccessories', 4, 'What you get by achieving your goals is not as important as what you become by achieving your goals.', '2023-11-07 21:05:03', NULL, 0);
INSERT INTO `image_info` VALUES (88, 'https://drive.kazumashim1.com/VideoGames', 2, 'Navicat Data Modeler is a powerful and cost-effective database design tool which helps you build high-quality conceptual, logical and physical data models.', '2023-11-04 21:08:17', NULL, 0);
INSERT INTO `image_info` VALUES (89, 'https://image.psheila.com/HouseholdKitchenAppliances', 4, 'I destroy my enemies when I make them my friends.', '2023-11-04 09:51:26', NULL, 0);
INSERT INTO `image_info` VALUES (90, 'http://drive.chungyin59.com/Baby', 1, 'Success consists of going from failure to failure without loss of enthusiasm.', '2023-11-05 17:03:01', NULL, 0);
INSERT INTO `image_info` VALUES (91, 'http://image.lanqiu8.com/Beauty', 4, 'Navicat 15 has added support for the system-wide dark mode. Actually it is just in an idea when feel oneself can achieve and cannot achieve. The Synchronize to Database function will                  ', '2023-11-02 11:15:25', NULL, 0);
INSERT INTO `image_info` VALUES (92, 'https://drive.boydeborah.com/FilmSupplies', 1, 'To successfully establish a new connection to local/remote server - no matter via SSL, SSH or HTTP, set the database login information in the General tab.', '2023-11-05 16:23:11', NULL, 0);
INSERT INTO `image_info` VALUES (93, 'http://drive.yyamato8.com/CDsVinyl', 0, 'In the Objects tab, you can use the List List, Detail Detail and ER Diagram ER Diagram buttons to change the object view. Always keep your eyes open. Keep watching. Because whatever                   ', '2023-11-03 16:20:44', NULL, 0);
INSERT INTO `image_info` VALUES (94, 'http://image.moolois.com/HouseholdKitchenAppliances', 4, 'Navicat authorizes you to make connection to remote servers running on different platforms (i.e. Windows, macOS, Linux and UNIX), and supports PAM and GSSAPI authentication.                           ', '2023-11-20 02:18:53', NULL, 0);
INSERT INTO `image_info` VALUES (95, 'http://image.yamky4.com/BeautyPersonalCare', 2, 'Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from.', '2023-11-08 16:48:03', NULL, 0);
INSERT INTO `image_info` VALUES (96, 'https://drive.stevenvarga.com/CollectiblesFineArt', 5, 'Import Wizard allows you to import data to tables/collections from CSV, TXT, XML, DBF and more.', '2023-11-12 11:47:38', NULL, 0);
INSERT INTO `image_info` VALUES (97, 'http://drive.billyd1969.com/ToolsHomeDecoration', 3, 'Optimism is the one quality more associated with success and happiness than any other.', '2023-11-14 08:59:58', NULL, 0);
INSERT INTO `image_info` VALUES (98, 'https://image.forjesus.com/MusicalInstrument', 3, 'A query is used to extract data from the database in a readable format according to the user\'s request.', '2023-11-01 11:31:21', NULL, 0);
INSERT INTO `image_info` VALUES (99, 'http://drive.zitao69.com/VideoGames', 5, 'SQL Editor allows you to create and edit SQL text, prepare and execute selected queries. All journeys have secret destinations of which the traveler is unaware. SSH serves to prevent                  ', '2023-11-13 21:36:54', NULL, 0);
INSERT INTO `image_info` VALUES (100, 'https://drive.jiezhong.com/PetSupplies', 1, 'Optimism is the one quality more associated with success and happiness than any other.', '2023-11-06 20:19:13', NULL, 0);
